package com.airyisea.bos.domain.basic;
// Generated 2016-12-23 18:06:50 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Standard generated by hbm2java
 */
@Entity
@Table(name="t_standard"
    ,catalog="bos"
)
public class Standard  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1110409747377938384L;
	private Integer id;
     private String name;
     private Integer minWeight;
     private Integer maxWeight;
     private Integer minLength;
     private Integer maxLength;
     private Date operatingTime;
     private String operator;
     private String operatorStation;

    public Standard() {
    }

	
    public Standard(Date operatingTime) {
        this.operatingTime = operatingTime;
    }
    public Standard(String name, Integer minWeight, Integer maxWeight, Integer minLength, Integer maxLength, Date operatingTime, String operator, String operatorStation) {
       this.name = name;
       this.minWeight = minWeight;
       this.maxWeight = maxWeight;
       this.minLength = minLength;
       this.maxLength = maxLength;
       this.operatingTime = operatingTime;
       this.operator = operator;
       this.operatorStation = operatorStation;
    }
   
     @Id @GeneratedValue
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="minweight")
    public Integer getMinWeight() {
        return this.minWeight;
    }
    
    public void setMinWeight(Integer minWeight) {
        this.minWeight = minWeight;
    }
    
    @Column(name="maxweight")
    public Integer getMaxWeight() {
        return this.maxWeight;
    }
    
    public void setMaxWeight(Integer maxWeight) {
        this.maxWeight = maxWeight;
    }
    
    @Column(name="minlength")
    public Integer getMinLength() {
        return this.minLength;
    }
    
    public void setMinLength(Integer minLength) {
        this.minLength = minLength;
    }
    
    @Column(name="maxlength")
    public Integer getMaxLength() {
        return this.maxLength;
    }
    
    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="operatingtime", nullable=false, length=0)
    public Date getOperatingTime() {
        return this.operatingTime;
    }
    
    public void setOperatingTime(Date operatingTime) {
        this.operatingTime = operatingTime;
    }
    
    @Column(name="operator", length=20)
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    
    @Column(name="operatorstation")
    public String getOperatorStation() {
        return this.operatorStation;
    }
    
    public void setOperatorStation(String operatorStation) {
        this.operatorStation = operatorStation;
    }




}


